// RUN: %clang_cc1 -std=c++26 -fcontracts -fcontracts-p3097 -emit-llvm -o /dev/null %s
// XFAIL: *
// GENERATED by src/pubs/impl/p3850impl/contract-matrix-gen.py -- do not edit.
// Regenerate with:  contract-matrix-gen.py emit --group readers
//
// Who needs a function's contracts, crossed with what state they are in and what the predicate contains.
//
// Three axes.  READER: the function's own definition, a P3097
// interface wrapper, a P3595 caller-side check, constant evaluation, or another
// contract's predicate.  PRODUCER: defined, declared-only, pure virtual,
// out-of-line, explicitly instantiated.  PREDICATE KIND: a constant, a
// non-dependent call, a type-dependent expression, or a reference to a member of
// the dependent class.
//
// The third axis is the one worth defending.  GCC-34 needed a predicate
// containing anything substitution would rewrite, and a plain call sufficed;
// CLANG-14 needs one that is value-*dependent* when parsed.  `pre (true)`
// reproduces neither, because a predicate that is already a constant is usable
// without substitution at all.  Two defects one axis apart -- and that axis is
// why hand-picked shapes kept catching one and missing the other.
//
// Every shape is measured at both the syntax and the codegen phase, because
// CLANG-14 is invisible to -fsyntax-only.
//
// Mirror: g++.dg/contracts/cpp26/matrix-readers-openbug-clang-14.C
//
// EXPECTED TO FAIL: every case below currently trips CLANG-14, an open
// issue on this branch.  The mirror compiles them, so the two files carry
// opposite expectations on purpose.


int mxhelper ();
constexpr int mxhelper_ce () { return 0; }

// --------------------------------------------------------------------------
// A pure virtual in a class template read by its P3097 interface
// wrapper.  There is no definition to instantiate, so the wrapper is the only
// thing that will ever need these contracts.  This is where GCC-34 lived, and
// where CLANG-14 still does for the dependent predicate.
//
// Predicate kind: dependent -- `sizeof (T) > 0`.  Phase: codegen.
// --------------------------------------------------------------------------
namespace pure_virtual__dependent__codegen {

template <class T> struct A {
  virtual int get () const pre (sizeof (T) > 0) = 0;
  int n;
};
struct D : A<int> { int get () const override { return n; } };
int use (A<int> &a) { return a.get (); }
}  // namespace pure_virtual__dependent__codegen

// --------------------------------------------------------------------------
// A pure virtual in a class template read by its P3097 interface
// wrapper.  There is no definition to instantiate, so the wrapper is the only
// thing that will ever need these contracts.  This is where GCC-34 lived, and
// where CLANG-14 still does for the dependent predicate.
//
// Predicate kind: member -- `n >= 0`.  Phase: codegen.
// --------------------------------------------------------------------------
namespace pure_virtual__member__codegen {

template <class T> struct A {
  virtual int get () const pre (n >= 0) = 0;
  int n;
};
struct D : A<int> { int get () const override { return n; } };
int use (A<int> &a) { return a.get (); }
}  // namespace pure_virtual__member__codegen

// --------------------------------------------------------------------------
// A pure virtual reached after an explicit instantiation of the class
// template, which instantiates the members' declarations on a different schedule
// from an implicit use.
//
// Predicate kind: dependent -- `sizeof (T) > 0`.  Phase: codegen.
// --------------------------------------------------------------------------
namespace pure_virtual_explicit_inst__dependent__codegen {

template <class T> struct A {
  virtual int get () const pre (sizeof (T) > 0) = 0;
  int n;
};
template struct A<int>;
struct D : A<int> { int get () const override { return n; } };
int use (A<int> &a) { return a.get (); }
}  // namespace pure_virtual_explicit_inst__dependent__codegen

// --------------------------------------------------------------------------
// A pure virtual reached after an explicit instantiation of the class
// template, which instantiates the members' declarations on a different schedule
// from an implicit use.
//
// Predicate kind: member -- `n >= 0`.  Phase: codegen.
// --------------------------------------------------------------------------
namespace pure_virtual_explicit_inst__member__codegen {

template <class T> struct A {
  virtual int get () const pre (n >= 0) = 0;
  int n;
};
template struct A<int>;
struct D : A<int> { int get () const override { return n; } };
int use (A<int> &a) { return a.get (); }
}  // namespace pure_virtual_explicit_inst__member__codegen
