// RUN: %clang_cc1 -std=c++26 -fcontracts -fcontracts-p4283 -fsyntax-only -verify %s
// GENERATED by src/pubs/impl/p3850impl/contract-matrix-gen.py -- do not edit.
// Regenerate with:  contract-matrix-gen.py emit --group sfinae
//
// Contracts and the immediate context: deduction, overload resolution, concepts and unevaluated operands.
//
// Contracts are not part of a function's type or signature, so
// they must be invisible to deduction, overload resolution, partial ordering and
// concept satisfaction.  What they are NOT is SFINAE-friendly: once a function is
// odr-used its contracts are needed ([dcl.contract.func]/9), and a predicate that
// cannot be substituted is a hard error -- never a quiet substitution failure that
// selects a different overload.
//
// The unevaluated-operand cells are the ones worth understanding before editing
// this file.  Contract instantiation runs from the odr-use path in both compilers
// (Clang's InstantiateFunctionContractsOnUse, and GCC's maybe_instantiate_contracts
// since GCC-34), and an unevaluated operand does not odr-use.  If that ever stops
// being true, an ill-formed predicate escapes the one specialization it belongs to
// and starts breaking concept checks in code that never mentioned contracts.
//
// Mirror: g++.dg/contracts/cpp26/matrix-sfinae-p4283.C

// expected-no-diagnostics

struct HasIt { bool nonexistent () const { return true; } };

// --------------------------------------------------------------------------
// P4283 evaluates a contract's requires-clause before substituting
// its predicate, and discards the contract when it is not satisfied.  So a
// predicate that could never be substituted is unreachable behind an unsatisfied
// clause -- the contract is gone before anyone looks at it.  If the order were
// the other way round this would be a hard error.
// --------------------------------------------------------------------------
namespace p4283_unsatisfied_discards_before_substituting {

template <class T> concept is_class = __is_class (T);

template <class T>
int f (T t) pre requires (is_class<T>) (t.nonexistent ()) { return 1; }

int use () { return f (0); }
}  // namespace p4283_unsatisfied_discards_before_substituting
