// RUN: %clangxx -std=c++26 %s -fcontracts -fcontracts-p4283 -fcontract-evaluation-semantic=observe %libcxx_flags -o %t
// RUN: %t
// GENERATED by src/pubs/impl/p3850impl/contract-matrix-gen.py -- do not edit.
// Regenerate with:  contract-matrix-gen.py emit --group sfinae
//
// Contracts and the immediate context: deduction, overload resolution, concepts and unevaluated operands.
//
// Contracts are not part of a function's type or signature, so
// they must be invisible to deduction, overload resolution, partial ordering and
// concept satisfaction.  What they are NOT is SFINAE-friendly: once a function is
// odr-used its contracts are needed ([dcl.contract.func]/9), and a predicate that
// cannot be substituted is a hard error -- never a quiet substitution failure that
// selects a different overload.
//
// The unevaluated-operand cells are the ones worth understanding before editing
// this file.  Contract instantiation runs from the odr-use path in both compilers
// (Clang's InstantiateFunctionContractsOnUse, and GCC's maybe_instantiate_contracts
// since GCC-34), and an unevaluated operand does not odr-use.  If that ever stops
// being true, an ill-formed predicate escapes the one specialization it belongs to
// and starts breaking concept checks in code that never mentioned contracts.
//
// Mirror: g++.dg/contracts/cpp26/matrix-sfinae-p4283-run.C


// --------------------------------------------------------------------------
// Discarding a contract must not discard the function.  Checked at
// run time rather than by inspection, because a function that quietly stopped
// being called would look identical at compile time.
// --------------------------------------------------------------------------
namespace p4283_discarded_contract_leaves_function_callable {

template <class T> concept is_class = __is_class (T);

template <class T>
int twice (T v) pre requires (is_class<T>) (v > 0) { return v * 2; }

int check () { return twice (21) == 42 ? 0 : 1; }
}  // namespace p4283_discarded_contract_leaves_function_callable

int
main()
{
  if (int rc = p4283_discarded_contract_leaves_function_callable::check ())
    return 1 * 100 + rc;
  return 0;
}
