// RUN: %clang_cc1 -std=c++26 -fcontracts -fcontracts-p3400 -fsyntax-only -verify %s
// GENERATED by src/pubs/impl/p3850impl/contract-matrix-gen.py -- do not edit.
// Regenerate with:  contract-matrix-gen.py emit --group exceptspec
//
// Contracts must never change a function's exception specification.
//
// A contract assertion is not part of a function's interface,
// so nothing about it -- the predicate, whether the predicate can throw, a P3400
// label, a P3098 capture initializer, the chosen evaluation semantic, or the
// P3097 wrapper interposed on a virtual call -- may change what the exception
// specification says.
//
// Every cell compares a contracted construct against an uncontracted twin rather
// than against a literal answer.  `static_assert (noexcept (f ()) == false)` on
// its own would still pass if the compiler had lost the specification entirely;
// comparing against the twin says the contract changed nothing, which is the
// proposition actually at issue.
//
// The separate question -- what happens at run time when a contract does throw --
// is the `throwpaths` group.
//
// Mirror: g++.dg/contracts/cpp26/matrix-exceptspec-p3400.C

// expected-no-diagnostics

// --------------------------------------------------------------------------
// A P3400 label is an expression evaluated to choose the semantic.
// It sits syntactically inside the contract, so it is one more thing that could
// leak into the specification.
// --------------------------------------------------------------------------
namespace p3400_label_does_not_change_noexcept {

struct lbl_t { using assertion_control_object = lbl_t; };
constexpr lbl_t lbl{};

void plain () noexcept;
void guarded () noexcept pre<lbl> (true);

static_assert (noexcept (guarded ()) == noexcept (plain ()));
static_assert (noexcept (guarded ()) == true);
}  // namespace p3400_label_does_not_change_noexcept
