// RUN: %clang_cc1 -std=c++26 -fcontracts -fcontracts-p4283 -verify-ignore-unexpected=note -fsyntax-only -verify %s
// GENERATED by src/pubs/impl/p3850impl/contract-matrix-gen.py -- do not edit.
// Regenerate with:  contract-matrix-gen.py emit --group sfinae
//
// Contracts and the immediate context: deduction, overload resolution, concepts and unevaluated operands.
//
// Contracts are not part of a function's type or signature, so
// they must be invisible to deduction, overload resolution, partial ordering and
// concept satisfaction.  What they are NOT is SFINAE-friendly: once a function is
// odr-used its contracts are needed ([dcl.contract.func]/9), and a predicate that
// cannot be substituted is a hard error -- never a quiet substitution failure that
// selects a different overload.
//
// The unevaluated-operand cells are the ones worth understanding before editing
// this file.  Contract instantiation runs from the odr-use path in both compilers
// (Clang's InstantiateFunctionContractsOnUse, and GCC's maybe_instantiate_contracts
// since GCC-34), and an unevaluated operand does not odr-use.  If that ever stops
// being true, an ill-formed predicate escapes the one specialization it belongs to
// and starts breaking concept checks in code that never mentioned contracts.
//
// Mirror: g++.dg/contracts/cpp26/matrix-sfinae-p4283-errors.C


struct HasIt { bool nonexistent () const { return true; } };

// --------------------------------------------------------------------------
// Control for the cell above: a satisfied requires-clause leaves
// the predicate in place, so an ill-formed one is still an error.  Together the
// pair pin the ordering rather than just the happy path.
// --------------------------------------------------------------------------
namespace p4283_satisfied_still_substitutes_the_predicate {

template <class T> struct scalarish { static constexpr bool value = false; };
template <> struct scalarish<int> { static constexpr bool value = true; };
template <class T> concept is_scalar = scalarish<T>::value;

template <class T>
int f (T t) pre requires (is_scalar<T>) (t.nonexistent ()) { return 1; }  // expected-error {{}}

int use () { return f (0); }
}  // namespace p4283_satisfied_still_substitutes_the_predicate
