// RUN: %clang_cc1 -std=c++26 -fcontracts -fcontracts-p3098 -fsyntax-only -verify %s
// GENERATED by src/pubs/impl/p3850impl/contract-matrix-gen.py -- do not edit.
// Regenerate with:  contract-matrix-gen.py emit --group exceptspec
//
// Contracts must never change a function's exception specification.
//
// A contract assertion is not part of a function's interface,
// so nothing about it -- the predicate, whether the predicate can throw, a P3400
// label, a P3098 capture initializer, the chosen evaluation semantic, or the
// P3097 wrapper interposed on a virtual call -- may change what the exception
// specification says.
//
// Every cell compares a contracted construct against an uncontracted twin rather
// than against a literal answer.  `static_assert (noexcept (f ()) == false)` on
// its own would still pass if the compiler had lost the specification entirely;
// comparing against the twin says the contract changed nothing, which is the
// proposition actually at issue.
//
// The separate question -- what happens at run time when a contract does throw --
// is the `throwpaths` group.
//
// Mirror: g++.dg/contracts/cpp26/matrix-exceptspec-p3098.C

// expected-no-diagnostics

int may_throw ();                 // not noexcept
int never_throws () noexcept;
bool pred_may_throw ();           // a predicate that is itself not noexcept
bool pred_never_throws () noexcept;

// --------------------------------------------------------------------------
// A postcondition capture is built on entry and can throw from its
// initializer, which is a genuinely new way for a contract to raise -- and still
// must not appear in the specification.
// --------------------------------------------------------------------------
namespace p3098_capture_does_not_change_noexcept {

int plain (int) noexcept;
int guarded (int p) noexcept post [old = may_throw ()] (old >= 0);
int guarded2 (int p) post [old = may_throw ()] (old >= 0);

static_assert (noexcept (guarded (0)) == true);
static_assert (noexcept (guarded (0)) == noexcept (plain (0)));
static_assert (noexcept (guarded2 (0)) == false);
}  // namespace p3098_capture_does_not_change_noexcept
