// RUN: %clang_cc1 -std=c++26 -fcontracts -fcontracts-p3097 -fsyntax-only -verify %s
// GENERATED by src/pubs/impl/p3850impl/contract-matrix-gen.py -- do not edit.
// Regenerate with:  contract-matrix-gen.py emit --group exceptspec
//
// Contracts must never change a function's exception specification.
//
// A contract assertion is not part of a function's interface,
// so nothing about it -- the predicate, whether the predicate can throw, a P3400
// label, a P3098 capture initializer, the chosen evaluation semantic, or the
// P3097 wrapper interposed on a virtual call -- may change what the exception
// specification says.
//
// Every cell compares a contracted construct against an uncontracted twin rather
// than against a literal answer.  `static_assert (noexcept (f ()) == false)` on
// its own would still pass if the compiler had lost the specification entirely;
// comparing against the twin says the contract changed nothing, which is the
// proposition actually at issue.
//
// The separate question -- what happens at run time when a contract does throw --
// is the `throwpaths` group.
//
// Mirror: g++.dg/contracts/cpp26/matrix-exceptspec-p3097.C

// expected-no-diagnostics

// --------------------------------------------------------------------------
// P3097 wraps a virtual call in a contract wrapper.  D4298 says
// the wrapper inherits the function's exception specification verbatim, so that
// marking it noexcept on the strength of its contracts alone could not force
// termination on a legitimate exception from the real implementation.  That is a
// claim in a comment; this is the test for it.
// --------------------------------------------------------------------------
namespace p3097_virtual_spec_preserved {

struct Plain { virtual void f () noexcept; virtual void g (); };
struct Guarded {
  virtual void f () noexcept pre (true);
  virtual void g () pre (true);
};

static_assert (noexcept (((Guarded *) nullptr)->f ()) == true);
static_assert (noexcept (((Guarded *) nullptr)->g ()) == false);
static_assert (noexcept (((Guarded *) nullptr)->f ())
               == noexcept (((Plain *) nullptr)->f ()));
}  // namespace p3097_virtual_spec_preserved
