// RUN: %clangxx -std=c++26 %s -fcontracts-p3850 -fcontract-evaluation-semantic=observe %libcxx_flags -o %t
// RUN: %t
// GENERATED by src/pubs/impl/p3850impl/contract-matrix-gen.py -- do not edit.
// Regenerate with:  contract-matrix-gen.py emit --group throwpaths
//
// Exceptions raised from every way a contract assertion can materialise.
//
// The proposition is not "the exception is catchable at the
// call site".  Under P2900 an exception escaping a predicate is itself a contract
// violation, reported with detection_mode evaluation_exception, after which the
// observe semantic continues normally.  So what each cell checks is that its
// materialisation routes into the handler that way -- rather than escaping,
// terminating, or being swallowed with no report -- and that control returns and
// object lifetimes are undisturbed afterwards.
//
// A throwing violation *handler* is the separate case: that exception is the
// program's own and must propagate out of the contracted call.
//
// Materialisations covered: precondition, postcondition, postcondition with a
// result binding, contract_assert, a P3098 capture initializer, a P3098 capturing
// predicate, a P3097 interface contract in the virtual wrapper, a constructor and
// a destructor.  Every cell is measured at -O0 and -O2, because a check that is
// correct at -O0 and optimised away at -O2 is a correctness bug that no
// syntax-only test can see.
//
// Mirror: g++.dg/contracts/cpp26/matrix-throwpaths-p3850-run.C


#include <contracts>

namespace mx {

struct Boom { int tag; };
struct HandlerBoom { };

int viol = 0;                  // violations reported
int excepts = 0;               // ... of which came from a throwing predicate
bool handler_throws = false;   // make the handler itself raise

int live = 0;                  // outstanding Tracked objects, for leak checks

struct Tracked {
  Tracked () { ++live; }
  Tracked (const Tracked &) { ++live; }
  ~Tracked () { --live; }
};

inline void reset () { viol = 0; excepts = 0; handler_throws = false; }

inline bool boom () { throw Boom{1}; return true; }

}  // namespace mx

void
handle_contract_violation (const std::contracts::contract_violation &v)
{
  ++mx::viol;
  if (v.detection_mode ()
      == std::contracts::detection_mode::evaluation_exception)
    ++mx::excepts;
  if (mx::handler_throws)
    throw mx::HandlerBoom{};
}

// --------------------------------------------------------------------------
// A precondition whose predicate exits via an exception is a
// violation with detection_mode evaluation_exception.  Under observe the
// exception must not escape the call and the function must run normally
// afterwards -- the check is that the count moved AND that control returned.
// --------------------------------------------------------------------------
namespace throwing_precondition_is_reported_not_escaped {

int f (int x) pre (mx::boom ()) { return x + 1; }

int check ()
{
  mx::reset ();
  int r = f (1);
  if (r != 2) return 1;                 // the body must still have run
  if (mx::viol != 1) return 2;
  if (mx::excepts != 1) return 3;       // reported as evaluation_exception
  return 0;
}
}  // namespace throwing_precondition_is_reported_not_escaped

// --------------------------------------------------------------------------
// The same for a postcondition, which runs on the way out and so
// takes a different path through the function's epilogue.
// --------------------------------------------------------------------------
namespace throwing_postcondition_is_reported {

int f (int x) post (r: mx::boom ()) { return x + 1; }

int check ()
{
  mx::reset ();
  if (f (1) != 2) return 1;
  if (mx::viol != 1) return 2;
  if (mx::excepts != 1) return 3;
  return 0;
}
}  // namespace throwing_postcondition_is_reported

// --------------------------------------------------------------------------
// A contract_assert in the body, which unlike pre and post is not
// attached to the function's interface at all.
// --------------------------------------------------------------------------
namespace throwing_contract_assert_is_reported {

int f (int x) { contract_assert (mx::boom ()); return x + 1; }

int check ()
{
  mx::reset ();
  if (f (1) != 2) return 1;
  if (mx::viol != 1) return 2;
  if (mx::excepts != 1) return 3;
  return 0;
}
}  // namespace throwing_contract_assert_is_reported

// --------------------------------------------------------------------------
// P3098 splits a postcondition into an on-entry capture and an
// on-exit predicate, so the capture initializer is a place a contract can raise
// *before* the body has run.  That is a materialisation with no equivalent in
// P2900, and the one most likely to have its own path.
// --------------------------------------------------------------------------
namespace throwing_capture_initializer_is_reported {

int f (int x) post [old = mx::boom ()] (old >= 0) { return x + 1; }

int check ()
{
  mx::reset ();
  if (f (1) != 2) return 1;
  if (mx::viol != 1) return 2;
  if (mx::excepts != 1) return 3;
  return 0;
}
}  // namespace throwing_capture_initializer_is_reported

// --------------------------------------------------------------------------
// The other half of a capturing postcondition: the capture is
// built successfully and the predicate throws on the way out.
// --------------------------------------------------------------------------
namespace throwing_capturing_predicate_is_reported {

int f (int x) post [old = x] (mx::boom ()) { return x + 1; }

int check ()
{
  mx::reset ();
  if (f (1) != 2) return 1;
  if (mx::viol != 1) return 2;
  if (mx::excepts != 1) return 3;
  return 0;
}
}  // namespace throwing_capturing_predicate_is_reported

// --------------------------------------------------------------------------
// P3097 evaluates an interface contract in a wrapper around the
// vtable dispatch, so a throwing predicate there raises from inside the wrapper
// rather than from the function's own prologue.
// --------------------------------------------------------------------------
namespace throwing_virtual_interface_contract_is_reported {

struct B {
  virtual int get () const pre (mx::boom ()) { return 7; }
  virtual ~B () = default;
};
struct D : B {
  int get () const override { return 7; }
};

int check ()
{
  mx::reset ();
  D d;
  B &b = d;
  if (b.get () != 7) return 1;
  if (mx::viol != 1) return 2;
  if (mx::excepts != 1) return 3;
  return 0;
}
}  // namespace throwing_virtual_interface_contract_is_reported

// --------------------------------------------------------------------------
// A contract on a constructor raises while the object is still
// being built.  Under observe construction has to complete anyway, and nothing
// may be left half-destroyed -- so the live-object count is checked as well as
// the violation count.
// --------------------------------------------------------------------------
namespace throwing_constructor_contract_is_reported {

struct S {
  mx::Tracked t;
  S () pre (mx::boom ()) { }
};

int check ()
{
  mx::reset ();
  int before = mx::live;
  { S s; if (mx::viol != 1) return 1; }
  if (mx::excepts != 1) return 2;
  if (mx::live != before) return 3;     // the member was destroyed exactly once
  return 0;
}
}  // namespace throwing_constructor_contract_is_reported

// --------------------------------------------------------------------------
// A contract on a destructor raises during unwinding of the
// enclosing scope, which is the most constrained place a contract can throw
// from.
// --------------------------------------------------------------------------
namespace throwing_destructor_contract_is_reported {

struct S {
  ~S () pre (mx::boom ()) { }
};

int check ()
{
  mx::reset ();
  { S s; }
  if (mx::viol != 1) return 1;
  if (mx::excepts != 1) return 2;
  return 0;
}
}  // namespace throwing_destructor_contract_is_reported

// --------------------------------------------------------------------------
// A throwing predicate must not disturb objects already alive at
// the point of the call.  Counts them across the call rather than inspecting
// codegen, so a stray destructor call shows up as a number.
// --------------------------------------------------------------------------
namespace live_objects_survive_a_throwing_precondition {

int f (mx::Tracked, int x) pre (mx::boom ()) { return x + 1; }

int check ()
{
  mx::reset ();
  int before = mx::live;
  {
    mx::Tracked keep;
    if (f (mx::Tracked{}, 1) != 2) return 1;
    if (mx::live != before + 1) return 2;   // just `keep`
  }
  if (mx::live != before) return 3;
  if (mx::viol != 1) return 4;
  return 0;
}
}  // namespace live_objects_survive_a_throwing_precondition

// --------------------------------------------------------------------------
// When the violation handler itself throws under observe, the
// exception is the program's, not the contract machinery's, and must propagate
// out of the contracted call to the nearest handler.  Distinct from a throwing
// predicate, which the machinery converts into a report.
// --------------------------------------------------------------------------
namespace throwing_handler_propagates_from_precondition {

int f (int x) pre (x > 0) { return x + 1; }

int check ()
{
  mx::reset ();
  mx::handler_throws = true;
  try {
      (void) f (-1);                    // violated, so the handler runs
      return 1;                         // must not get here
  } catch (const mx::HandlerBoom &) {
      if (mx::viol != 1) return 2;
      return 0;
  } catch (...) {
      return 3;                         // must be the handler's exception
  }
}
}  // namespace throwing_handler_propagates_from_precondition

// --------------------------------------------------------------------------
// The same from a postcondition, where the exception has to escape
// past the return-value machinery rather than the prologue.
// --------------------------------------------------------------------------
namespace throwing_handler_propagates_from_postcondition {

int f (int x) post (r: r > 0) { return x; }

int check ()
{
  mx::reset ();
  mx::handler_throws = true;
  try {
      (void) f (-1);
      return 1;
  } catch (const mx::HandlerBoom &) {
      if (mx::viol != 1) return 2;
      return 0;
  } catch (...) {
      return 3;
  }
}
}  // namespace throwing_handler_propagates_from_postcondition

// --------------------------------------------------------------------------
// Both at once: the predicate raises, the machinery reports it,
// and the handler raises in turn.  The handler's exception is the one that must
// escape -- the predicate's has already been consumed into the report.
// --------------------------------------------------------------------------
namespace throwing_handler_from_a_throwing_predicate {

int f (int x) pre (mx::boom ()) { return x + 1; }

int check ()
{
  mx::reset ();
  mx::handler_throws = true;
  try {
      (void) f (1);
      return 1;
  } catch (const mx::HandlerBoom &) {
      if (mx::excepts != 1) return 2;   // reported as evaluation_exception
      return 0;
  } catch (const mx::Boom &) {
      return 3;                         // the predicate's must not escape
  } catch (...) {
      return 4;
  }
}
}  // namespace throwing_handler_from_a_throwing_predicate

int
main()
{
  if (int rc = throwing_precondition_is_reported_not_escaped::check ())
    return 1 * 100 + rc;
  if (int rc = throwing_postcondition_is_reported::check ())
    return 2 * 100 + rc;
  if (int rc = throwing_contract_assert_is_reported::check ())
    return 3 * 100 + rc;
  if (int rc = throwing_capture_initializer_is_reported::check ())
    return 4 * 100 + rc;
  if (int rc = throwing_capturing_predicate_is_reported::check ())
    return 5 * 100 + rc;
  if (int rc = throwing_virtual_interface_contract_is_reported::check ())
    return 6 * 100 + rc;
  if (int rc = throwing_constructor_contract_is_reported::check ())
    return 7 * 100 + rc;
  if (int rc = throwing_destructor_contract_is_reported::check ())
    return 8 * 100 + rc;
  if (int rc = live_objects_survive_a_throwing_precondition::check ())
    return 9 * 100 + rc;
  if (int rc = throwing_handler_propagates_from_precondition::check ())
    return 10 * 100 + rc;
  if (int rc = throwing_handler_propagates_from_postcondition::check ())
    return 11 * 100 + rc;
  if (int rc = throwing_handler_from_a_throwing_predicate::check ())
    return 12 * 100 + rc;
  return 0;
}
