// RUN: %clang_cc1 -std=c++26 -fcontracts -fcontract-configuration-file=%S/matrix-readers-caller.json -fsyntax-only -verify %s
// GENERATED by src/pubs/impl/p3850impl/contract-matrix-gen.py -- do not edit.
// Regenerate with:  contract-matrix-gen.py emit --group readers
//
// Who needs a function's contracts, crossed with what state they are in and what the predicate contains.
//
// Three axes.  READER: the function's own definition, a P3097
// interface wrapper, a P3595 caller-side check, constant evaluation, or another
// contract's predicate.  PRODUCER: defined, declared-only, pure virtual,
// out-of-line, explicitly instantiated.  PREDICATE KIND: a constant, a
// non-dependent call, a type-dependent expression, or a reference to a member of
// the dependent class.
//
// The third axis is the one worth defending.  GCC-34 needed a predicate
// containing anything substitution would rewrite, and a plain call sufficed;
// CLANG-14 needs one that is value-*dependent* when parsed.  `pre (true)`
// reproduces neither, because a predicate that is already a constant is usable
// without substitution at all.  Two defects one axis apart -- and that axis is
// why hand-picked shapes kept catching one and missing the other.
//
// Every shape is measured at both the syntax and the codegen phase, because
// CLANG-14 is invisible to -fsyntax-only.
//
// Mirror: g++.dg/contracts/cpp26/matrix-readers-caller.C

// expected-warning@*:* {{caller-side contract checking is configured}}

int mxhelper ();
constexpr int mxhelper_ce () { return 0; }

// --------------------------------------------------------------------------
// A free function template that is declared, called and never defined,
// read by a P3595 caller-side check at the call site.  No virtual and no class:
// the second, independent route to the defect GCC-34 fixed.
//
// Predicate kind: constant -- `true`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_declared_only_free__constant__syntax {

template <class T> int f (T t) pre (true);
int use () { return f (0); }
}  // namespace caller_side_declared_only_free__constant__syntax

// --------------------------------------------------------------------------
// A free function template that is declared, called and never defined,
// read by a P3595 caller-side check at the call site.  No virtual and no class:
// the second, independent route to the defect GCC-34 fixed.
//
// Predicate kind: call -- `mxhelper () == 0`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_declared_only_free__call__syntax {

template <class T> int f (T t) pre (mxhelper () == 0);
int use () { return f (0); }
}  // namespace caller_side_declared_only_free__call__syntax

// --------------------------------------------------------------------------
// A free function template that is declared, called and never defined,
// read by a P3595 caller-side check at the call site.  No virtual and no class:
// the second, independent route to the defect GCC-34 fixed.
//
// Predicate kind: dependent -- `sizeof (T) > 0`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_declared_only_free__dependent__syntax {

template <class T> int f (T t) pre (sizeof (T) > 0);
int use () { return f (0); }
}  // namespace caller_side_declared_only_free__dependent__syntax

// --------------------------------------------------------------------------
// The same for a member of a class template, whose contracts arrive as
// a placeholder rather than being written on the declaration that is called.
//
// Predicate kind: constant -- `true`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_declared_only_member__constant__syntax {

template <class T> struct A {
  int get () const pre (true);
  int n;
};
int use (A<int> &a) { return a.get (); }
}  // namespace caller_side_declared_only_member__constant__syntax

// --------------------------------------------------------------------------
// The same for a member of a class template, whose contracts arrive as
// a placeholder rather than being written on the declaration that is called.
//
// Predicate kind: call -- `mxhelper () == 0`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_declared_only_member__call__syntax {

template <class T> struct A {
  int get () const pre (mxhelper () == 0);
  int n;
};
int use (A<int> &a) { return a.get (); }
}  // namespace caller_side_declared_only_member__call__syntax

// --------------------------------------------------------------------------
// The same for a member of a class template, whose contracts arrive as
// a placeholder rather than being written on the declaration that is called.
//
// Predicate kind: dependent -- `sizeof (T) > 0`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_declared_only_member__dependent__syntax {

template <class T> struct A {
  int get () const pre (sizeof (T) > 0);
  int n;
};
int use (A<int> &a) { return a.get (); }
}  // namespace caller_side_declared_only_member__dependent__syntax

// --------------------------------------------------------------------------
// The same for a member of a class template, whose contracts arrive as
// a placeholder rather than being written on the declaration that is called.
//
// Predicate kind: member -- `n >= 0`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_declared_only_member__member__syntax {

template <class T> struct A {
  int get () const pre (n >= 0);
  int n;
};
int use (A<int> &a) { return a.get (); }
}  // namespace caller_side_declared_only_member__member__syntax

// --------------------------------------------------------------------------
// Control for the two above: caller-side checking of a function that
// IS defined here, so its contracts were substituted by the definition and the
// call site must reuse rather than resubstitute them.
//
// Predicate kind: constant -- `true`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_defined__constant__syntax {

template <class T> int f (T t) pre (true) { return 0; }
int use () { return f (0); }
}  // namespace caller_side_defined__constant__syntax

// --------------------------------------------------------------------------
// Control for the two above: caller-side checking of a function that
// IS defined here, so its contracts were substituted by the definition and the
// call site must reuse rather than resubstitute them.
//
// Predicate kind: call -- `mxhelper () == 0`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_defined__call__syntax {

template <class T> int f (T t) pre (mxhelper () == 0) { return 0; }
int use () { return f (0); }
}  // namespace caller_side_defined__call__syntax

// --------------------------------------------------------------------------
// Control for the two above: caller-side checking of a function that
// IS defined here, so its contracts were substituted by the definition and the
// call site must reuse rather than resubstitute them.
//
// Predicate kind: dependent -- `sizeof (T) > 0`.  Phase: syntax.
//
// Expected difference between the two compilers:
// Clang accepts caller-side configuration but does not implement caller-
// side checking, so it warns that the configuration will not be honoured
// (see p3595-caller-unimplemented-warn.cpp). GCC implements it and is
// silent. Intended, not a finding.
// --------------------------------------------------------------------------
namespace caller_side_defined__dependent__syntax {

template <class T> int f (T t) pre (sizeof (T) > 0) { return 0; }
int use () { return f (0); }
}  // namespace caller_side_defined__dependent__syntax
